/**
 * Sample job postings.
 *
 * These are ILLUSTRATIVE listings for a fictional set of companies, used to
 * exercise the marketplace, filters and matching engine. They are marked
 * `source: "seed"` so they can be identified and purged before real listings
 * are ingested — a demo posting must never be mistaken for a live vacancy.
 */

export type CompanySeed = {
  name: string;
  slug: string;
  industry: string;
  sizeBand: string;
  about: string;
};

export const COMPANIES: CompanySeed[] = [
  { name: "Northwind Systems", slug: "northwind-systems", industry: "Software Products", sizeBand: "201-500", about: "A product engineering company building supply-chain software for Indian manufacturers." },
  { name: "Kaveri Analytics", slug: "kaveri-analytics", industry: "Data & Analytics", sizeBand: "51-200", about: "An analytics consultancy serving banking and insurance clients." },
  { name: "Meridian Health Group", slug: "meridian-health-group", industry: "Healthcare", sizeBand: "1000+", about: "A multi-speciality hospital network across southern India." },
  { name: "Sarvottam Infra", slug: "sarvottam-infra", industry: "Construction & Infrastructure", sizeBand: "500-1000", about: "An infrastructure contractor working on roads, bridges and urban water projects." },
  { name: "Prayaan Logistics", slug: "prayaan-logistics", industry: "Logistics", sizeBand: "201-500", about: "A third-party logistics provider operating warehousing and last-mile delivery." },
  { name: "Bluecrest Financial", slug: "bluecrest-financial", industry: "Financial Services", sizeBand: "51-200", about: "A boutique financial advisory and audit firm." },
  { name: "Anantara Design Studio", slug: "anantara-design-studio", industry: "Design", sizeBand: "11-50", about: "A design studio working on brand and product design for consumer companies." },
  { name: "Sankalp Learning", slug: "sankalp-learning", industry: "Education", sizeBand: "51-200", about: "A school network and teacher-training organisation." },
  { name: "Tejas Manufacturing", slug: "tejas-manufacturing", industry: "Manufacturing", sizeBand: "500-1000", about: "An auto-components manufacturer supplying OEMs." },
  { name: "Vistara Cloud", slug: "vistara-cloud", industry: "Cloud Services", sizeBand: "201-500", about: "A managed cloud and DevOps services provider." },
];

export type JobSeed = {
  slug: string;
  title: string;
  companySlug: string;
  occupationSlug?: string;
  description: string;
  responsibilities: string[];
  employmentType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP" | "APPRENTICESHIP" | "FREELANCE";
  remoteType: "ONSITE" | "HYBRID" | "REMOTE";
  region: string;
  city: string;
  experienceMin: number;
  experienceMax?: number;
  educationRequired?: string;
  skillsRequired: string[];
  skillsPreferred?: string[];
  salaryMin?: number;
  salaryMax?: number;
  disclosed: boolean;
};

const L = 100_000;

export const JOBS: JobSeed[] = [
  {
    slug: "backend-engineer-northwind-bengaluru",
    title: "Backend Engineer",
    companySlug: "northwind-systems",
    occupationSlug: "software-developer",
    description:
      "Build and maintain the services behind our supply-chain platform. You'll own features end to end, from design discussion through to production monitoring.",
    responsibilities: [
      "Design and build REST APIs used by our web and mobile clients",
      "Write and review code with an emphasis on readability over cleverness",
      "Own the reliability of the services you ship, including on-call rotation",
      "Work directly with product and design rather than through a spec handoff",
    ],
    employmentType: "FULL_TIME",
    remoteType: "HYBRID",
    region: "Karnataka",
    city: "Bengaluru",
    experienceMin: 2,
    experienceMax: 5,
    educationRequired: "Any degree, or demonstrable equivalent experience",
    skillsRequired: ["Python", "SQL", "REST APIs", "Git", "PostgreSQL"],
    skillsPreferred: ["Docker", "AWS", "Redis"],
    salaryMin: 12 * L,
    salaryMax: 22 * L,
    disclosed: true,
  },
  {
    slug: "junior-frontend-developer-northwind-pune",
    title: "Junior Frontend Developer",
    companySlug: "northwind-systems",
    occupationSlug: "software-developer",
    description:
      "A first or second role for someone who has built things and wants to work on a product used daily by hundreds of warehouse teams. We'll pair you with a senior engineer for your first three months.",
    responsibilities: [
      "Build interfaces in React with an eye on how they behave on slow connections",
      "Turn design files into working, accessible components",
      "Fix defects reported by our support team",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Maharashtra",
    city: "Pune",
    experienceMin: 0,
    experienceMax: 2,
    educationRequired: "Any degree, or a portfolio of deployed work",
    skillsRequired: ["JavaScript", "React", "HTML", "CSS", "Git"],
    skillsPreferred: ["TypeScript", "Figma"],
    salaryMin: 4 * L,
    salaryMax: 7 * L,
    disclosed: true,
  },
  {
    slug: "data-analyst-kaveri-hyderabad",
    title: "Data Analyst",
    companySlug: "kaveri-analytics",
    occupationSlug: "data-analyst",
    description:
      "Work with banking clients to turn transaction and customer data into decisions. Strong SQL matters more to us than a specific degree.",
    responsibilities: [
      "Write SQL to answer client questions and validate the answers",
      "Build and maintain dashboards clients actually use",
      "Present findings to client teams who need a decision, not a chart",
    ],
    employmentType: "FULL_TIME",
    remoteType: "HYBRID",
    region: "Telangana",
    city: "Hyderabad",
    experienceMin: 1,
    experienceMax: 4,
    educationRequired: "Any degree",
    skillsRequired: ["SQL", "Excel", "Power BI", "Communication"],
    skillsPreferred: ["Python", "Statistics", "Tableau"],
    salaryMin: 6 * L,
    salaryMax: 11 * L,
    disclosed: true,
  },
  {
    slug: "senior-data-scientist-kaveri-remote",
    title: "Senior Data Scientist",
    companySlug: "kaveri-analytics",
    occupationSlug: "data-scientist",
    description:
      "Lead modelling work for insurance clients — pricing, churn and fraud detection. Remote within India, with quarterly travel to client sites.",
    responsibilities: [
      "Own model development from problem framing through to deployment",
      "Mentor two junior analysts",
      "Explain model behaviour to client stakeholders who are accountable for the outcome",
    ],
    employmentType: "FULL_TIME",
    remoteType: "REMOTE",
    region: "Telangana",
    city: "Remote (India)",
    experienceMin: 5,
    experienceMax: 9,
    educationRequired: "Degree in a quantitative discipline",
    skillsRequired: ["Python", "Machine Learning", "SQL", "Statistics", "Pandas"],
    skillsPreferred: ["PyTorch", "AWS", "Docker"],
    salaryMin: 24 * L,
    salaryMax: 38 * L,
    disclosed: true,
  },
  {
    slug: "staff-nurse-meridian-chennai",
    title: "Staff Nurse — Intensive Care",
    companySlug: "meridian-health-group",
    occupationSlug: "nurse",
    description:
      "Join the critical care team at our Chennai unit. Rotational shifts with a shift differential for nights, and structured clinical development.",
    responsibilities: [
      "Provide direct nursing care to critically ill patients",
      "Monitor and record vitals and administer prescribed treatment",
      "Support the clinical team during procedures and emergencies",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Tamil Nadu",
    city: "Chennai",
    experienceMin: 1,
    experienceMax: 6,
    educationRequired: "BSc Nursing or GNM, with State Nursing Council registration",
    skillsRequired: ["Patient Care", "Nursing Care", "Emergency Care", "Infection Control"],
    salaryMin: 3 * L,
    salaryMax: 5.5 * L,
    disclosed: true,
  },
  {
    slug: "site-engineer-sarvottam-jaipur",
    title: "Site Engineer — Roads",
    companySlug: "sarvottam-infra",
    occupationSlug: "civil-engineer",
    description:
      "Supervise execution on a state highway upgrade project. Site-based role with company accommodation provided.",
    responsibilities: [
      "Supervise daily construction activity and subcontractor teams",
      "Check quality against specification and record deviations",
      "Prepare progress measurements and support billing",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Rajasthan",
    city: "Jaipur",
    experienceMin: 2,
    experienceMax: 6,
    educationRequired: "BE/BTech or Diploma in Civil Engineering",
    skillsRequired: ["AutoCAD", "Surveying", "Project Estimation", "Quality Control"],
    skillsPreferred: ["STAAD Pro", "Project Management"],
    salaryMin: 4.5 * L,
    salaryMax: 8 * L,
    disclosed: true,
  },
  {
    slug: "supply-chain-executive-prayaan-nagpur",
    title: "Supply Chain Executive",
    companySlug: "prayaan-logistics",
    occupationSlug: "supply-chain-manager",
    description:
      "Coordinate inbound and outbound movement across our central India warehouse network. Suits someone comfortable with spreadsheets and with a warehouse floor.",
    responsibilities: [
      "Plan daily dispatch schedules and track exceptions",
      "Maintain inventory accuracy and investigate discrepancies",
      "Coordinate with transporters and resolve delivery failures",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Maharashtra",
    city: "Nagpur",
    experienceMin: 1,
    experienceMax: 4,
    educationRequired: "Any degree",
    skillsRequired: ["Supply Chain", "Excel", "Inventory Management", "Communication"],
    skillsPreferred: ["SQL", "Logistics Planning"],
    salaryMin: 3.5 * L,
    salaryMax: 6 * L,
    disclosed: true,
  },
  {
    slug: "warehouse-supervisor-prayaan-delhi",
    title: "Warehouse Supervisor",
    companySlug: "prayaan-logistics",
    description:
      "Run a shift at our Delhi NCR fulfilment centre. Class 12 is enough — we care about whether you can run a team and hit a dispatch window.",
    responsibilities: [
      "Supervise a shift team of 20–30 people",
      "Ensure picking and dispatch targets are met accurately",
      "Enforce safety procedures on the floor",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Delhi",
    city: "New Delhi",
    experienceMin: 2,
    experienceMax: 8,
    educationRequired: "Class 12 or above",
    skillsRequired: ["Leadership", "Inventory Management", "Safety Procedures", "Teamwork"],
    salaryMin: 2.8 * L,
    salaryMax: 4.5 * L,
    disclosed: true,
  },
  {
    slug: "audit-associate-bluecrest-mumbai",
    title: "Audit Associate",
    companySlug: "bluecrest-financial",
    occupationSlug: "chartered-accountant",
    description:
      "Statutory audit work across mid-sized manufacturing and services clients. Open to qualified CAs and to semi-qualified candidates with completed articleship.",
    responsibilities: [
      "Execute audit fieldwork under a manager's supervision",
      "Prepare working papers and draft financial statements",
      "Liaise with client finance teams on queries",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Maharashtra",
    city: "Mumbai",
    experienceMin: 0,
    experienceMax: 3,
    educationRequired: "CA qualified, or CA Inter with completed articleship",
    skillsRequired: ["Accounting", "Auditing", "Excel", "Ind AS"],
    skillsPreferred: ["GST", "Income Tax"],
    salaryMin: 6 * L,
    salaryMax: 11 * L,
    disclosed: true,
  },
  {
    slug: "accountant-bluecrest-indore",
    title: "Accountant",
    companySlug: "bluecrest-financial",
    occupationSlug: "accountant",
    description:
      "Handle books, GST returns and TDS for a portfolio of small business clients. Practical Tally experience matters more than the degree.",
    responsibilities: [
      "Maintain books of accounts for assigned clients",
      "Prepare and file GST and TDS returns",
      "Support month-end and year-end closing",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Madhya Pradesh",
    city: "Indore",
    experienceMin: 1,
    experienceMax: 5,
    educationRequired: "B.Com or equivalent",
    skillsRequired: ["Accounting", "Tally", "GST", "Excel"],
    skillsPreferred: ["Income Tax", "Bookkeeping"],
    salaryMin: 2.4 * L,
    salaryMax: 4.2 * L,
    disclosed: true,
  },
  {
    slug: "product-designer-anantara-remote",
    title: "Product Designer",
    companySlug: "anantara-design-studio",
    occupationSlug: "ui-ux-designer",
    description:
      "Work across two or three client products at a time. We hire on portfolio — send us three pieces of work and the reasoning behind them.",
    responsibilities: [
      "Run discovery with client teams and their users",
      "Design flows and interfaces in Figma, through to developer handoff",
      "Test designs with real users before they ship",
    ],
    employmentType: "FULL_TIME",
    remoteType: "REMOTE",
    region: "Karnataka",
    city: "Remote (India)",
    experienceMin: 2,
    experienceMax: 6,
    educationRequired: "Portfolio required; degree optional",
    skillsRequired: ["Figma", "UI Design", "UX Research", "Prototyping"],
    skillsPreferred: ["Typography", "Communication"],
    salaryMin: 9 * L,
    salaryMax: 18 * L,
    disclosed: true,
  },
  {
    slug: "graphic-design-intern-anantara-bengaluru",
    title: "Graphic Design Intern",
    companySlug: "anantara-design-studio",
    occupationSlug: "graphic-designer",
    description:
      "Six-month paid internship. Suitable for students or recent graduates with a portfolio, including self-taught designers.",
    responsibilities: [
      "Support brand and campaign design work",
      "Prepare files for print and digital delivery",
      "Present your own concepts in internal reviews",
    ],
    employmentType: "INTERNSHIP",
    remoteType: "HYBRID",
    region: "Karnataka",
    city: "Bengaluru",
    experienceMin: 0,
    experienceMax: 1,
    educationRequired: "Any; portfolio required",
    skillsRequired: ["Adobe Illustrator", "Adobe Photoshop", "Typography"],
    skillsPreferred: ["Figma", "InDesign"],
    salaryMin: 20_000 * 12,
    salaryMax: 30_000 * 12,
    disclosed: true,
  },
  {
    slug: "pgt-mathematics-sankalp-lucknow",
    title: "PGT Mathematics",
    companySlug: "sankalp-learning",
    occupationSlug: "school-teacher",
    description:
      "Teach mathematics to Classes 11 and 12 at our Lucknow campus. B.Ed required; CTET qualified candidates preferred.",
    responsibilities: [
      "Plan and deliver mathematics lessons for senior classes",
      "Assess student work and provide meaningful feedback",
      "Support board examination preparation",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Uttar Pradesh",
    city: "Lucknow",
    experienceMin: 2,
    experienceMax: 10,
    educationRequired: "Postgraduate degree in Mathematics with B.Ed",
    skillsRequired: ["Teaching", "Curriculum Design", "Communication"],
    skillsPreferred: ["Public Speaking"],
    salaryMin: 4 * L,
    salaryMax: 7.5 * L,
    disclosed: true,
  },
  {
    slug: "maintenance-technician-tejas-coimbatore",
    title: "Maintenance Technician",
    companySlug: "tejas-manufacturing",
    occupationSlug: "automobile-technician",
    description:
      "Preventive and breakdown maintenance on our machining lines. ITI holders are encouraged to apply; we run a structured six-month induction.",
    responsibilities: [
      "Carry out preventive maintenance schedules",
      "Diagnose and repair machine breakdowns",
      "Maintain maintenance records and spare part inventory",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Tamil Nadu",
    city: "Coimbatore",
    experienceMin: 1,
    experienceMax: 6,
    educationRequired: "ITI or Diploma in a relevant trade",
    skillsRequired: ["Fitting", "Blueprint Reading", "Safety Procedures", "Problem Solving"],
    skillsPreferred: ["CNC Machining", "Electrical Wiring"],
    salaryMin: 2.2 * L,
    salaryMax: 4 * L,
    disclosed: true,
  },
  {
    slug: "welder-apprentice-tejas-coimbatore",
    title: "Welder — Apprentice",
    companySlug: "tejas-manufacturing",
    occupationSlug: "welder",
    description:
      "A one-year apprenticeship under the National Apprenticeship scheme, with a stipend and a strong likelihood of a permanent role on completion.",
    responsibilities: [
      "Learn and perform MIG and TIG welding on production components",
      "Follow safety procedures without exception",
      "Support quality checks on completed welds",
    ],
    employmentType: "APPRENTICESHIP",
    remoteType: "ONSITE",
    region: "Tamil Nadu",
    city: "Coimbatore",
    experienceMin: 0,
    experienceMax: 1,
    educationRequired: "ITI in Welder trade, or Class 10 with willingness to train",
    skillsRequired: ["Welding", "Safety Procedures"],
    salaryMin: 1.4 * L,
    salaryMax: 1.9 * L,
    disclosed: true,
  },
  {
    slug: "devops-engineer-vistara-remote",
    title: "DevOps Engineer",
    companySlug: "vistara-cloud",
    occupationSlug: "devops-engineer",
    description:
      "Manage cloud infrastructure and delivery pipelines for our managed-services clients. Fully remote with an on-call rotation shared across the team.",
    responsibilities: [
      "Build and maintain CI/CD pipelines",
      "Manage AWS infrastructure as code",
      "Respond to production incidents during your rotation",
    ],
    employmentType: "FULL_TIME",
    remoteType: "REMOTE",
    region: "Karnataka",
    city: "Remote (India)",
    experienceMin: 3,
    experienceMax: 7,
    educationRequired: "Any degree or equivalent experience",
    skillsRequired: ["Linux", "Docker", "AWS", "CI/CD", "Terraform"],
    skillsPreferred: ["Kubernetes", "Monitoring", "Shell Scripting"],
    salaryMin: 14 * L,
    salaryMax: 26 * L,
    disclosed: true,
  },
  {
    slug: "cloud-support-engineer-vistara-kochi",
    title: "Cloud Support Engineer",
    companySlug: "vistara-cloud",
    description:
      "First-line support for cloud infrastructure issues. A good entry point into cloud work for someone with Linux fundamentals and no prior cloud role.",
    responsibilities: [
      "Triage and resolve infrastructure tickets",
      "Escalate complex issues with proper diagnostics attached",
      "Document recurring issues and fixes",
    ],
    employmentType: "FULL_TIME",
    remoteType: "HYBRID",
    region: "Kerala",
    city: "Kochi",
    experienceMin: 0,
    experienceMax: 3,
    educationRequired: "Any degree or diploma",
    skillsRequired: ["Linux", "Communication", "Problem Solving"],
    skillsPreferred: ["AWS", "Shell Scripting", "Monitoring"],
    salaryMin: 3.5 * L,
    salaryMax: 6.5 * L,
    disclosed: true,
  },
  {
    slug: "digital-marketing-executive-sankalp-remote",
    title: "Digital Marketing Executive",
    companySlug: "sankalp-learning",
    occupationSlug: "digital-marketer",
    description:
      "Run admissions campaigns across search and social for our school network. Remote, with measurable targets on cost per enquiry.",
    responsibilities: [
      "Plan and run paid campaigns on Google and Meta",
      "Improve landing page conversion in collaboration with design",
      "Report weekly on spend, enquiries and cost per enquiry",
    ],
    employmentType: "FULL_TIME",
    remoteType: "REMOTE",
    region: "Uttar Pradesh",
    city: "Remote (India)",
    experienceMin: 1,
    experienceMax: 4,
    educationRequired: "Any degree",
    skillsRequired: ["Digital Marketing", "SEO", "Google Analytics", "Content Writing"],
    skillsPreferred: ["Social Media", "Communication"],
    salaryMin: 3.5 * L,
    salaryMax: 7 * L,
    disclosed: true,
  },
  {
    slug: "customer-support-associate-northwind-jaipur",
    title: "Customer Support Associate",
    companySlug: "northwind-systems",
    occupationSlug: "customer-support-executive",
    description:
      "Support warehouse teams using our platform, over chat and phone. Full training provided; Class 12 is enough to apply.",
    responsibilities: [
      "Resolve customer queries over chat, email and phone",
      "Log issues accurately and escalate where needed",
      "Contribute to the internal help documentation",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Rajasthan",
    city: "Jaipur",
    experienceMin: 0,
    experienceMax: 3,
    educationRequired: "Class 12 or above",
    skillsRequired: ["Communication", "Customer Service", "Problem Solving"],
    skillsPreferred: ["CRM", "Teamwork"],
    salaryMin: 2.2 * L,
    salaryMax: 3.6 * L,
    disclosed: true,
  },
  {
    slug: "electrician-sarvottam-ahmedabad",
    title: "Electrician",
    companySlug: "sarvottam-infra",
    occupationSlug: "electrician",
    description:
      "Site electrical installation and maintenance across our Gujarat projects. ITI Electrician trade required; state licence preferred.",
    responsibilities: [
      "Install and maintain site electrical systems",
      "Diagnose and repair faults safely",
      "Maintain compliance with site safety procedures",
    ],
    employmentType: "FULL_TIME",
    remoteType: "ONSITE",
    region: "Gujarat",
    city: "Ahmedabad",
    experienceMin: 1,
    experienceMax: 8,
    educationRequired: "ITI in Electrician trade",
    skillsRequired: ["Electrical Wiring", "Safety Procedures", "Blueprint Reading"],
    salaryMin: 2 * L,
    salaryMax: 4.2 * L,
    disclosed: true,
  },
];
